# "модули" ---------------------------------------------------------------------


# кнопка стола

<ButtonStol@Button>:
    font_size: '14'
    size_hint_x: .4
    background_normal: ''
    background_color: (.12, .12, .17, 1)


# ...

<LabelStol@Label>:
    text_size: self.size
    halign: 'left'
    valign: 'middle'
    font_size: '12'


# ...

<Box10@BoxLayout>:
    spacing: 10


# ...

<BoxVert@BoxLayout>:
    orientation: 'vertical'


# Экраны -----------------------------------------------------------------------


# основной экран

<RootScreen>:
    id: RootScreenId
    BoxLayout:
        orientation: 'vertical'
        canvas:
            Color:
                rgba: .17, .18, .24, .9
            Rectangle:
                pos: self.pos
                size: self.size

        time_label_1: time_label_1
        time_label_2: time_label_2

        type_1: type_1
        type_2: type_2
        type_3: type_3
        type_4: type_4
        type_5: type_5
        type_6: type_6
        type_7: type_7
        type_8: type_8
        type_9: type_9
        type_10: type_10
        type_11: type_11
        type_12: type_12
        type_13: type_13
        type_14: type_14
        type_15: type_15
        type_16: type_16
        type_17: type_17
        type_18: type_18
        type_19: type_19
        type_20: type_20
        type_21: type_21
        type_22: type_22
        type_23: type_23
        type_24: type_24
        type_25: type_25
        type_B: type_B
        type_K: type_K

        time_1: time_1
        time_2: time_2
        time_3: time_3
        time_4: time_4
        time_5: time_5
        time_6: time_6
        time_7: time_7
        time_8: time_8
        time_9: time_9
        time_10: time_10
        time_11: time_11
        time_12: time_12
        time_13: time_13
        time_14: time_14
        time_15: time_15
        time_16: time_16
        time_17: time_17
        time_18: time_18
        time_19: time_19
        time_20: time_20
        time_21: time_21
        time_22: time_22
        time_23: time_23
        time_24: time_24
        time_25: time_25
        time_B: time_B
        time_K: time_K

        hookah_list: hookah_list

        # Toolbar
        
        AnchorLayout:
            id: Toolbar
            size_hint_y: None
            canvas:
                Color:
                    rgba: .17, .18, .24, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

            BoxLayout:
                Image:
                    source: 'logo.png'
                    size_hint: .2, 1

                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: .7
                    Label:
                        text: 'HOOKAH KEEPER'
                        font_size: '40sp'
                        text_size: self.size
                        halign: 'left'
                        valign: 'bottom'
                    Label:
                        size_hint_y: .5
                        text: ' by Max Myslivets for Sfera Club'
                        font_size: '14sp'
                        text_size: self.size
                        halign: 'left'
                        valign: 'top'
                
                BoxLayout:
                    orientation: 'vertical'

                    Label:
                        id: time_label_1
                        font_size: '20'
                        text_size: self.size
                        halign: 'center'
                        valign: 'bottom'
                    Label:
                        id: time_label_2
                        font_size: '30'
                        text_size: self.size
                        halign: 'center'
                        valign: 'middle'
                    
                BoxLayout:
                    spacing: 2
                    size_hint_x: .1
                    Button:
                        on_release: root.manager.current = 'Add Hookah Screen'

                BoxLayout:
                    spacing: 2
                    size_hint: None, None
                    size: 68, 32
                    pos_hint: {'top': 1}
                    
                    MDIconButton:
                        id: min_window_button
                        icon: "window-minimize"

                        user_font_size: "14sp"
                        pos_hint: {'top': 1}
                        
                        on_release: app.stop()
                
                    MDIconButton:

                        id: close_window_button
                        icon: "window-close"

                        user_font_size: "14sp"
                        pos_hint: {'top': 1}

                        on_release: app.stop()


        # Столы

        BoxLayout:
            orientation: 'horizontal'
            padding: 20, 0, 0, 0
            BoxLayout:
                BoxLayout:
                    padding: 5, 20, 5, 20
                    spacing: 2
                    orientation: 'vertical'

                    Box10:
                        ButtonStol:
                            text: '1'
                            on_release: root.func(self.text)
                        BoxVert:
                            LabelStol:
                                id: type_1
                                text: 'None'
                            LabelStol:
                                id: time_1
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '2'
                        BoxVert:
                            LabelStol:
                                id: type_2
                                text: 'None'
                            LabelStol:
                                id: time_2
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '3'
                        BoxVert:
                            LabelStol:
                                id: type_3
                                text: 'None'
                            LabelStol:
                                id: time_3
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '4'
                        BoxVert:
                            LabelStol:
                                id: type_4
                                text: 'None'
                            LabelStol:
                                id: time_4
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '5'
                        BoxVert:
                            LabelStol:
                                id: type_5
                                text: 'None'
                            LabelStol:
                                id: time_5
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '6'
                        BoxVert:
                            LabelStol:
                                id: type_6
                                text: 'None'
                            LabelStol:
                                id: time_6
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '7'
                        BoxVert:
                            LabelStol:
                                id: type_7
                                text: 'None'
                            LabelStol:
                                id: time_7
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '8'
                        BoxVert:
                            LabelStol:
                                id: type_8
                                text: 'None'
                            LabelStol:
                                id: time_8
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '9'
                        BoxVert:
                            LabelStol:
                                id: type_9
                                text: 'None'
                            LabelStol:
                                id: time_9
                                text: '0 / 0'

                BoxLayout:
                    padding: 5, 20, 5, 20
                    spacing: 2
                    orientation: 'vertical'

                    Box10:
                        ButtonStol:
                            text: '10'
                        BoxVert:
                            LabelStol:
                                id: type_10
                                text: 'None'
                            LabelStol:
                                id: time_10
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '11'
                        BoxVert:
                            LabelStol:
                                id: type_11
                                text: 'None'
                            LabelStol:
                                id: time_11
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '12'
                        BoxVert:
                            LabelStol:
                                id: type_12
                                text: 'None'
                            LabelStol:
                                id: time_12
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '13'
                        BoxVert:
                            LabelStol:
                                id: type_13
                                text: 'None'
                            LabelStol:
                                id: time_13
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '14'
                        BoxVert:
                            LabelStol:
                                id: type_14
                                text: 'None'
                            LabelStol:
                                id: time_14
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '15'
                        BoxVert:
                            LabelStol:
                                id: type_15
                                text: 'None'
                            LabelStol:
                                id: time_15
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '16'
                        BoxVert:
                            LabelStol:
                                id: type_16
                                text: 'None'
                            LabelStol:
                                id: time_16
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '17'
                        BoxVert:
                            LabelStol:
                                id: type_17
                                text: 'None'
                            LabelStol:
                                id: time_17
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '18'
                        BoxVert:
                            LabelStol:
                                id: type_18
                                text: 'None'
                            LabelStol:
                                id: time_18
                                text: '0 / 0'

                BoxLayout:
                    padding: 5, 20, 5, 20
                    spacing: 2
                    orientation: 'vertical'

                    Box10:
                        ButtonStol:
                            text: '19'
                        BoxVert:
                            LabelStol:
                                id: type_19
                                text: 'None'
                            LabelStol:
                                id: time_19
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '20'
                        BoxVert:
                            LabelStol:
                                id: type_20
                                text: 'None'
                            LabelStol:
                                id: time_20
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '21'
                        BoxVert:
                            LabelStol:
                                id: type_21
                                text: 'None'
                            LabelStol:
                                id: time_21
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '22'
                        BoxVert:
                            LabelStol:
                                id: type_22
                                text: 'None'
                            LabelStol:
                                id: time_22
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '23'
                        BoxVert:
                            LabelStol:
                                id: type_23
                                text: 'None'
                            LabelStol:
                                id: time_23
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '24'
                        BoxVert:
                            LabelStol:
                                id: type_24
                                text: 'None'
                            LabelStol:
                                id: time_24
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: '25'
                        BoxVert:
                            LabelStol:
                                id: type_25
                                text: 'None'
                            LabelStol:
                                id: time_25
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: 'Б'
                        BoxVert:
                            LabelStol:
                                id: type_B
                                text: 'None'
                            LabelStol:
                                id: time_B
                                text: '0 / 0'

                    Box10:
                        ButtonStol:
                            text: 'К'
                        BoxVert:
                            LabelStol:
                                id: type_K
                                text: 'None'
                            LabelStol:
                                id: time_K
                                text: '0 / 0'
                

            # Данные о заказах

            BoxLayout:
                size_hint_x: .5
                pos_hint: {'right': 1, 'center_y': .5}
                canvas:
                    Color:
                        rgba: .12, .12, .12, .2
                    Rectangle:
                        pos: self.pos
                        size: self.size
                
                BoxLayout:
                    ScrollView:
                        GridLayout:
                            cols: 1
                            size_hint_y: None
                            height: self.minimum_height
                            id: hookah_list

                            OneLineAvatarIconListItem:
                                text: 'one data'

                            OneLineAvatarIconListItem:
                                text: 'two data'


# Экран добавления заказа

<AddHookahScreen>:
    id: addhookahscreen
    BoxLayout:
        orientation: 'vertical'
        padding: 40, 0, 40, 40
        canvas:
            Color:
                rgba: .17, .18, .24, .9
            Rectangle:
                pos: self.pos
                size: self.size

        BoxLayout:
            size_hint_y: .4
            MDIconButton:
                size_hint: .05, .2
                pos_hint: {'center_y': .5, 'left': 1}
                icon: 'chevron-left'self.theme_cls.primary_palette = "Teal"
                on_release: root.functwo()
            Label:
                text: u'ДОБАВИТЬ ЗАКАЗ'
                font_size: '24'

        BoxLayout:

            BoxLayout:
                orientation: 'vertical'
                size_hint_x: .6
                spacing: 4

                Button:
                    size_hint_x: .3
                    font_size: '14'
                    background_normal: ''
                    background_color: (.12, .12, .17, 1)
                    text: u"КЛАССИЧЕСКИЙ"

                    on_release: app.classic_hookah()

                Button:
                    size_hint_x: .3
                    font_size: '14'
                    background_normal: ''
                    background_color: (.12, .12, .17, 1)
                    text: u'С ДОБАВКАМИ'

                    on_release: app.additive_hookah()

                Button:
                    size_hint_x: .3
                    font_size: '14'
                    background_normal: ''
                    background_color: (.12, .12, .17, 1)
                    text: u'НА ФРУКТЕ'

                    on_release: app.fruit_hookah()

                Button:
                    size_hint_x: .3
                    font_size: '14'
                    background_normal: ''
                    background_color: (.12, .12, .17, 1)
                    text: u'МИКС'

                    on_release: app.mix_hookah()

                Button:
                    size_hint_x: .3
                    font_size: '14'
                    background_normal: ''
                    background_color: (.12, .12, .17, 1)
                    text: u'ЗАМЕНА ЧАШИ'

                    on_release: app.replacement_hookah()
